# log level to write.5(debug); 4(info) ;3(warn); 2(error);1(fatal);0(panic).

gs:
    -
        id: 1
        dir: gs1
        logname: gs1.log
        loglevel: 5
        port: :7083
        ip: 127.0.0.1
        db: 127.0.0.1:27017
        dbName: gs
        gameType: [4,9,10,11,12,13,14,15,16,18,19,17]
        gameRecord: 0.0.0.0:11111
        cardConsume: http://120.77.173.104:10086
        gameReplayPath: /var/game_record/
        gameRecordLogPath: http://127.0.0.1:7072/log/add
#   example for more than 2 gs
#   -    
#       id: 2 
#       logname: gs.log,
#       loglevel: 5
#       port: 8081
#       ip: 127.0.0.2
#       db: 127.0.0.1:27017
#       dbName: gs
#       gameType:[0,1,2,3,4,5,6,7,8]
    
gate:
    -
        id: 1
        ip: 127.0.0.1
        port: 8081
        logname: gate1.log
        loglevel: 5
        db: 127.0.0.1:27017
        dbName: gate
        dir: gate1
        managerUrl: 127.0.0.1:9034
        gameRecordLogPath: http://127.0.0.1:7072/log/add
        moneyInitValue: 10000:88 #初始化货币 茶馆卡:房卡
        rechargeUrl: http://192.168.0.10:10086//充值服的url
        serverStatus: 2 # 1 受限 2 正常
        serverName: 测试服
        #    -
        #id: 2
        #ip: 127.0.0.1
        #port: 8081
        #logname: gate2.log
        #loglevel: 5
        #db: 127.0.0.1:27017
        #dbName: gate

login:
    ip: 127.0.0.1
    port: :9091
    logname: login.log
    loglevel: 5
    db: 127.0.0.1:27017
    dbName: login
    dir:    login1
gm: 
    dbName: gate
    db: 127.0.0.1:27017
    ip: 0.0.0.0
    port: 10101
    logname: gm.log
    loglevel: 5
    dir:    gm1
    toGate: http://127.0.0.1:8082/gm
    gameRecordLogPath: http://127.0.0.1:7072
stats:
    dbName: stat
    db: 127.0.0.1:27017

logserver:
    -
        id: 1
        dir: logserver1
        logname: logserver.log
        loglevel: 5
        port: :7072
        ip: 127.0.0.1
        db: 127.0.0.1:27017
        dbName: logs
